language: go

go:
  - 1.2
  - 1.3
  - tip

services:
  - rabbitmq

sudo: false

before_install:
  - go get github.com/kr/godep
  - export PATH=$HOME/gopath/bin:$PATH
  - export GOPATH=$(godep path):$GOPATH

before_script: cp config/worker.json.example config/worker.json

script:
  - godep go test ./...
  - godep go test -race ./...

matrix:
  allow_failures:
    - go: tip
