language: go
before_script: cp config/worker.example.json config/worker.json
script:
  - go test ./...
  - go test -race ./...
services:
  - rabbitmq
go:
  - 1.2
  - tip
matrix:
  allow_failures:
    - go: tip
