language: go
go: 1.4.1
sudo: false

services:
  - rabbitmq

before_install:
  - go get github.com/hamfist/deppy
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  # TODO: re-enable if/when the missing defs file issue is resolved
  # - go get github.com/laher/goxc
  - go install -a -race std

install: deppy restore

before_script: cp config/worker.json.example config/worker.json

script:
  - make test
  - make test-race
  - make save
  - git diff --exit-code
  - git diff --cached --exit-code
  - AMQP_URI=amqp:// POOL_SIZE=1 BUILD_API_URI=http://localhost:3000/script PROVIDER_NAME=fake PROVIDER_CONFIG=happy QUEUE_NAME=builds.test travis-worker &
  - AMQP_URI=amqp:// go test ./test
  # TODO: re-enable if/when the missing defs file issue is resolved
  # after_success:
  # - make crossbuild
after_success: bin/atlas-push
notifications:
  slack:
    rooms:
    - secure: "EeyaCTxwBPk17BC55brkWSQ9d8EEhKgJ9KHTIJzJnfGasXeUZWRzV80fT/eXcvWXnpq1GkP01xk1V60EC0G9XxLlHfCXbSJAAAr4vb0vadIB9LmVrWfOr1J2aRh4g5Vtk5zWBp2Qv4DVo8KdOVKR2MHI+bjtLFwZVvYmQSt+tzo=" 
