language: go
before_install:
  - go get github.com/kr/godep
  - export PATH=$HOME/gopath/bin:$PATH
  - export GOPATH=$(godep path):$GOPATH
before_script: cp config/worker.example.json config/worker.json
script:
  - godep go test ./...
  - godep go test -race ./...
services:
  - rabbitmq
go:
  - 1.2
  - tip
matrix:
  allow_failures:
    - go: tip
