language: go
go: 1.4.2
sudo: false

env:
  global:
  - INTEGRATION_TESTS_DISABLED=1
  - GOPATH="$HOME/gopath"
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"
  - UNAME="$(uname | tr '[:upper:]' '[:lower:]')"

before_install:
- go install -a -race std

script:
- gb build all
