language: go
go: 1.4.2
sudo: false

env:
  global:
  - INTEGRATION_TESTS_DISABLED=1
  - GOPATH="$HOME/gopath"
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"
  - UNAME="$(uname | tr '[:upper:]' '[:lower:]')"

install:
  - go get github.com/constabulary/gb/...

script:
  - gb build
  - make test
  - make test-race
  - git diff --exit-code || echo 'wat is goin on'
  - git diff --cached --exit-code || echo 'wat is goin on'
  - travis-worker --version
  - travis-worker -v
  - travis-worker --help
  - travis-worker -h
  - travis-worker --echo-config
