language: go
go: 1.4.2
sudo: false

env:
  global:
  - INTEGRATION_TESTS_DISABLED=1
  - GOPATH="$HOME/gopath"
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"
  - UNAME="$(uname | tr '[:upper:]' '[:lower:]')"

install:
  - go get github.com/constabulary/gb/...

script:
  - gb build
