language: haskell
ghc: 7.8
sudo: false
env:
  global:
  - GOPATH="$HOME/gopath"
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"
services:
- rabbitmq
before_install:
- curl -sL -o ~/gimme https://raw.githubusercontent.com/meatballhat/gimme/master/gimme
- chmod +x ~/gimme
- eval "$(~/gimme 1.4.1)"
- mkdir -p "$HOME/gopath/src/github.com/travis-ci/worker"
- rsync -az "${TRAVIS_BUILD_DIR}/" "$HOME/gopath/src/github.com/travis-ci/worker/"
- export TRAVIS_BUILD_DIR="$HOME/gopath/src/github.com/travis-ci/worker"
- cd "$HOME/gopath/src/github.com/travis-ci/worker"
- go get github.com/hamfist/deppy
- go get github.com/golang/lint/golint
- go get golang.org/x/tools/cmd/cover
- go get github.com/laher/goxc
- go install -a -race std
install:
- deppy restore
before_script:
- cp config/worker.json.example config/worker.json
script:
- make test
- make test-race
- make save
- git diff --exit-code
- git diff --cached --exit-code
- AMQP_URI=amqp:// POOL_SIZE=1 BUILD_API_URI=http://localhost:3000/script PROVIDER_NAME=fake PROVIDER_CONFIG=happy QUEUE_NAME=builds.test travis-worker &
- pushd test
- "[[ -d .cabal-sandbox/packages ]] || cabal sandbox init"
- cabal install -j
- cabal run
- popd
# after_success:
# - make crossbuild
cache:
  directories:
  - test/.cabal-sandbox
notifications:
  slack:
    rooms:
    - secure: "EeyaCTxwBPk17BC55brkWSQ9d8EEhKgJ9KHTIJzJnfGasXeUZWRzV80fT/eXcvWXnpq1GkP01xk1V60EC0G9XxLlHfCXbSJAAAr4vb0vadIB9LmVrWfOr1J2aRh4g5Vtk5zWBp2Qv4DVo8KdOVKR2MHI+bjtLFwZVvYmQSt+tzo=" 
